In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
df = pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\jan_datasets\\smartphone_addiction\\Smartphone_Usage_And_Addiction_Analysis_7500_Rows.csv")

In [57]:
df.head()

,transaction_id,user_id,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact,addiction_level,addicted_label
0,TXN00001,U00001,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes,NaN,0
1,TXN00002,U00002,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes,NaN,0
2,TXN00003,U00003,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No,Mild,0
3,TXN00004,U00004,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes,Moderate,1
4,TXN00005,U00005,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No,Severe,1

In [58]:
# plt.figure(figsize=(12,8))
# sns.heatmap(df.corr(),annot=True,cmap="coolwarm")
# plt.show()

In [59]:
df.dtypes

transaction_id              object
user_id                     object
age                          int64
gender                      object
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day        int64
app_opens_per_day            int64
weekend_screen_time        float64
stress_level                object
academic_work_impact        object
addiction_level             object
addicted_label               int64
dtype: object

In [60]:
df.isnull().sum()

transaction_id               0
user_id                      0
age                          0
gender                       0
daily_screen_time_hours      0
social_media_hours           0
gaming_hours                 0
work_study_hours             0
sleep_hours                  0
notifications_per_day        0
app_opens_per_day            0
weekend_screen_time          0
stress_level                 0
academic_work_impact         0
addiction_level            819
addicted_label               0
dtype: int64

In [61]:
df[df.duplicated()]

Empty DataFrame
Columns: [transaction_id, user_id, age, gender, daily_screen_time_hours, social_media_hours, gaming_hours, work_study_hours, sleep_hours, notifications_per_day, app_opens_per_day, weekend_screen_time, stress_level, academic_work_impact, addiction_level, addicted_label]
Index: []

In [62]:
df.drop(columns=["addiction_level"],inplace=True)

In [63]:
df.columns

Index(['transaction_id', 'user_id', 'age', 'gender', 'daily_screen_time_hours',
       'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours',
       'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time',
       'stress_level', 'academic_work_impact', 'addicted_label'],
      dtype='object')

In [64]:
df.dtypes

transaction_id              object
user_id                     object
age                          int64
gender                      object
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day        int64
app_opens_per_day            int64
weekend_screen_time        float64
stress_level                object
academic_work_impact        object
addicted_label               int64
dtype: object

In [65]:
df.drop(columns=["transaction_id","user_id"],inplace=True)

In [66]:
df["stress_level"].value_counts()

stress_level
High      2560
Low       2503
Medium    2437
Name: count, dtype: int64

In [67]:
df["academic_work_impact"].value_counts()

academic_work_impact
No     3753
Yes    3747
Name: count, dtype: int64

In [68]:
df.columns

Index(['age', 'gender', 'daily_screen_time_hours', 'social_media_hours',
       'gaming_hours', 'work_study_hours', 'sleep_hours',
       'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time',
       'stress_level', 'academic_work_impact', 'addicted_label'],
      dtype='object')

In [69]:
df.dtypes

age                          int64
gender                      object
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day        int64
app_opens_per_day            int64
weekend_screen_time        float64
stress_level                object
academic_work_impact        object
addicted_label               int64
dtype: object

In [70]:
df["academic_work_impact"].value_counts()

academic_work_impact
No     3753
Yes    3747
Name: count, dtype: int64

In [71]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [72]:
X.head()

,age,gender,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,stress_level,academic_work_impact
0,21,Male,3.23,2.01,0.89,4.55,7.55,248,154,3.95,Medium,Yes
1,24,Other,5.09,3.81,2.24,4.44,7.66,127,71,6.71,Medium,Yes
2,31,Other,6.06,1.36,3.83,2.35,4.92,44,106,8.68,High,No
3,32,Other,7.83,5.85,1.51,3.54,8.23,178,107,9.77,High,Yes
4,25,Male,9.96,5.92,3.42,5.27,6.21,136,177,12.55,Low,No

In [73]:
Y.head()

0    0
1    0
2    0
3    1
4    1
Name: addicted_label, dtype: int64

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["academic_work_impact"] = pd.DataFrame(le.fit_transform(X["academic_work_impact"]))

In [75]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [76]:
one_hot_cols = ['stress_level', 'gender']

In [77]:
ct = ColumnTransformer([("encoder",OneHotEncoder(),one_hot_cols)],remainder="passthrough")
X = pd.DataFrame(ct.fit_transform(X))

In [78]:
X.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
dtype: object

In [79]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [80]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [81]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)

In [82]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============KNN===========")
print("accuracy score",accuracy_score(Y_pred,Y_test)*100)
print("precision_score",precision_score(Y_pred,Y_test)*100)
print("recall_score",recall_score(Y_pred,Y_test)*100)
print("f1_score",f1_score(Y_pred,Y_test)*100)

=============KNN===========
accuracy score 85.46666666666667
precision_score 89.65517241379311
recall_score 89.48374760994264
f1_score 89.56937799043062

In [83]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)
Y_predict = nb.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============naive bayes===========")

print("accuracy score",accuracy_score(Y_predict,Y_test)*100)
print("precision_score",precision_score(Y_predict,Y_test)*100)
print("recall_score",recall_score(Y_predict,Y_test)*100)
print("f1_score",f1_score(Y_predict,Y_test)*100)

=============naive bayes===========
accuracy score 86.53333333333333
precision_score 87.93103448275862
recall_score 92.35412474849095
f1_score 90.0883218842002

In [85]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_predict2 = rf.predict(X_test)

In [86]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============Random Forest===========")

print("accuracy score",accuracy_score(Y_predict2,Y_test)*100)
print("precision_score",precision_score(Y_predict2,Y_test)*100)
print("recall_score",recall_score(Y_predict2,Y_test)*100)
print("f1_score",f1_score(Y_predict2,Y_test)*100)

=============Random Forest===========
accuracy score 92.80000000000001
precision_score 93.67816091954023
recall_score 95.88235294117648
f1_score 94.76744186046511