In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\lung_cancer_prediction\\survey lung cancer.csv.xls")
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [5]:
df.shape

(309, 16)

In [6]:
df.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

In [7]:
df[df.duplicated()]

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
99,M,56,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
100,M,58,2,1,1,1,1,1,2,2,2,2,1,1,1,YES
117,F,51,2,2,2,2,1,2,2,1,1,1,2,2,1,YES
199,F,55,2,1,1,2,2,2,2,2,2,1,1,2,2,YES
212,M,58,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
223,M,63,2,2,2,1,2,2,2,2,1,1,2,1,1,YES
256,M,60,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
275,M,64,2,2,2,2,2,1,1,1,2,1,1,2,2,YES
284,M,58,2,2,2,2,2,1,1,1,2,1,1,2,2,YES
285,F,58,2,2,2,2,1,2,1,1,1,2,2,2,1,YES
286,F,63,1,1,1,1,2,2,1,1,1,1,2,1,1,NO
287,F,51,2,2,2,2,1,2,1,1,1,1,2,2,1,YES
288,F,61,1,2,2,2,1,1,2,2,1,2,1,2,1,YES
289,F,61,2,1,1,1,2,2,2,1,1,1,2,1,1,YES
290,M,76,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
291,M,71,2,2,2,1,2,1,2,2,2,2,1,2,2,YES
292,M,69,1,1,2,1,1,2,1,2,2,2,2,2,1,YES
293,F,56,2,2,2,1,1,2,2,1,1,1,2,1,2,YES
294,M,67,1,1,1,2,1,2,1,2,1,2,2,1,2,YES
295,F,54,2,2,2,1,2,1,1,2,2,1,2,2,2,YES
296,M,63,1,2,1,1,1,2,1,2,2,2,2,1,1,YES
297,F,47,2,2,1,2,2,2,2,2,1,2,2,1,1,YES
298,M,62,2,1,2,1,1,2,1,2,2,2,2,1,2,YES
299,M,65,2,2,2,2,1,2,2,1,1,1,2,2,1,YES
300,F,63,2,2,2,2,2,2,2,2,1,2,2,2,2,YES
301,M,64,1,2,2,2,1,1,2,1,2,1,1,2,2,YES
302,F,65,2,2,2,2,1,2,1,2,1,2,2,2,1,YES
303,M,51,1,2,1,1,2,2,2,2,2,2,2,1,2,YES
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [8]:
df.drop_duplicates(keep="first",inplace=True)

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [GENDER, AGE, SMOKING, YELLOW_FINGERS, ANXIETY, PEER_PRESSURE, CHRONIC DISEASE, FATIGUE , ALLERGY , WHEEZING, ALCOHOL CONSUMING, COUGHING, SHORTNESS OF BREATH, SWALLOWING DIFFICULTY, CHEST PAIN, LUNG_CANCER]
Index: []

In [10]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [11]:
X.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1

In [12]:
Y.head()

0    YES
1    YES
2     NO
3     NO
4     NO
Name: LUNG_CANCER, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["GENDER"] = le.fit_transform(X["GENDER"])

In [14]:
X.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2
2,0,59,1,1,1,2,1,2,1,2,1,2,2,1,2
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2
4,0,63,1,2,1,1,1,1,1,2,1,2,2,1,1

In [15]:
le = LabelEncoder()
Y = pd.DataFrame(le.fit_transform(Y))

In [16]:
Y.head()

   0
0  1
1  1
2  0
3  0
4  0

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =  train_test_split(X,Y,test_size=0.2,random_state=4) #Same rows go into train/test every time.

In [18]:
X_train.shape

(220, 15)

In [19]:
X_test.shape

(56, 15)

In [20]:
df.shape

(276, 16)

In [21]:
X_train.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN
105,0,60,1,1,1,1,2,2,1,1,1,1,2,1,1
63,0,68,1,1,2,1,2,1,2,2,2,1,1,2,1
274,1,56,2,1,1,1,2,1,2,2,2,2,2,1,2
147,0,56,1,1,1,2,2,2,1,1,2,2,2,2,1
13,1,58,2,1,1,1,1,2,2,2,2,2,2,1,2

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

# fit_transform -> training data
# transform     -> test data

# fit_transform()
# Does 2 things together:
# Learns the min and max values from data (fit)
# Scales the data (transform)

# transform()
# Only scales using already learned min/max values.

In [23]:
# KNN

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) # any odd number
knn.fit(X_train,Y_train)

C:\Users\edwin\AppData\Roaming\Python\Python313\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [24]:
Y_pred = knn.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("===== KNN =====")

print("Accuracy score",accuracy_score(Y_pred,Y_test)*100)
print("Precision score",precision_score(Y_pred,Y_test)*100)
print("Recall score",recall_score(Y_pred,Y_test)*100)
print("F1 score",f1_score(Y_pred,Y_test)*100)

===== KNN =====
Accuracy score 87.5
Precision score 89.0909090909091
Recall score 98.0
F1 score 93.33333333333333

In [26]:
Y.value_counts()

0
1    238
0     38
Name: count, dtype: int64

### This is imbalanced dataset

In [27]:
# upsampling => 0 changed to 238
# downsampling => 238 changed to 0
# SMOTE

In [28]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)
Y_predict = nb.predict(X_test)

C:\Users\edwin\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [29]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== naive bayes =====")


print("accuracy score",accuracy_score(Y_predict,Y_test)*100)
print("precision_score",precision_score(Y_predict,Y_test)*100)
print("recall_score",recall_score(Y_predict,Y_test)*100)
print("f1_score",f1_score(Y_predict,Y_test)*100)

===== naive bayes =====
accuracy score 98.21428571428571
precision_score 98.18181818181819
recall_score 100.0
f1_score 99.08256880733946

In [30]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="gini",max_depth=4)
dt.fit(X_train,Y_train)
Y_predict1 = dt.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== decision tree =====")


print("accuracy score",accuracy_score(Y_predict1,Y_test)*100)
print("precision_score",precision_score(Y_predict1,Y_test)*100)
print("recall_score",recall_score(Y_predict1,Y_test)*100)
print("f1_score",f1_score(Y_predict1,Y_test)*100)

===== decision tree =====
accuracy score 94.64285714285714
precision_score 96.36363636363636
recall_score 98.14814814814815
f1_score 97.24770642201835

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_predict2 = rf.predict(X_test)

C:\Users\edwin\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [33]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== Random Forest =====")

print("accuracy score",accuracy_score(Y_predict2,Y_test)*100)
print("precision_score",precision_score(Y_predict2,Y_test)*100)
print("recall_score",recall_score(Y_predict2,Y_test)*100)
print("f1_score",f1_score(Y_predict2,Y_test)*100)

===== Random Forest =====
accuracy score 91.07142857142857
precision_score 92.72727272727272
recall_score 98.07692307692307
f1_score 95.32710280373831