In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\regression\\housing\\Housing.csv.xls")

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df.shape

(545, 13)

In [6]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [7]:
df[df.duplicated]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

In [8]:
Y=df.iloc[:,0]

In [9]:
Y.head()

0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64

In [10]:
X=df.iloc[:,1:]

In [11]:
X.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [12]:
cat_col=["mainroad","guestroom","basement","hotwaterheating","airconditioning","hotwaterheating","prefarea","furnishingstatus"]

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for i in cat_col:
    X[i]=pd.DataFrame(le.fit_transform(X[i]))

# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# ct=ColumnTransformer([("encoder",OneHotEncoder(),cat_col)],remainder="passthrough")
# X=pd.DataFrame(ct.fit_transform(X))

In [13]:
X.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.2,random_state=4)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=pd.DataFrame(scaler.fit_transform(X_train))
X_test=pd.DataFrame(scaler.transform(X_test))

In [16]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(X_train,Y_train)

LinearRegression()

In [17]:
Y_pred=lr.predict(X_test)

In [18]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred)*100)

r2_score 62.669866719647956

In [19]:
from sklearn.neighbors import KNeighborsRegressor

knn=KNeighborsRegressor()

knn.fit(X_train,Y_train)

KNeighborsRegressor()

In [20]:
Y_pred_knn=knn.predict(X_test)

In [21]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_knn)*100)

r2_score 53.617542724383526

In [22]:
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor()

dt.fit(X_train,Y_train)

DecisionTreeRegressor()

In [23]:
Y_pred_dt=dt.predict(X_test)

In [24]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_pred_dt,Y_test)*100)

r2_score 13.811800382222861

In [25]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()

rf.fit(X_train,Y_train)

RandomForestRegressor()

In [26]:
Y_pred_rf=rf.predict(X_test)

In [27]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_rf)*100)

r2_score 51.9469604735297

In [28]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor()

ada.fit(X_train,Y_train)

AdaBoostRegressor()

In [29]:
Y_pred_ada=ada.predict(X_test)

In [30]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_ada)*100)

r2_score 50.948569281393084

In [31]:
from xgboost import XGBRegressor

xgb=XGBRegressor()

xgb.fit(X_train,Y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [32]:
Y_pred_xgb=xgb.predict(X_test)

In [33]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_xgb)*100)

r2_score 47.48934507369995