In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\jan_datasets\\earthquake\\earthquake_data_tsunami.csv")

In [14]:
df.head()

,magnitude,cdi,mmi,sig,nst,dmin,gap,depth,latitude,longitude,Year,Month,tsunami
0,7.0,8,7,768,117,0.509,17.0,14.000,-9.7963,159.596,2022,11,1
1,6.9,4,4,735,99,2.229,34.0,25.000,-4.9559,100.738,2022,11,0
2,7.0,3,3,755,147,3.125,18.0,579.000,-20.0508,-178.346,2022,11,1
3,7.3,5,5,833,149,1.865,21.0,37.000,-19.2918,-172.129,2022,11,1
4,6.6,0,2,670,131,4.998,27.0,624.464,-25.5948,178.278,2022,11,1

In [15]:
df.dtypes

magnitude    float64
cdi            int64
mmi            int64
sig            int64
nst            int64
dmin         float64
gap          float64
depth        float64
latitude     float64
longitude    float64
Year           int64
Month          int64
tsunami        int64
dtype: object

In [16]:
df.isnull().sum()

magnitude    0
cdi          0
mmi          0
sig          0
nst          0
dmin         0
gap          0
depth        0
latitude     0
longitude    0
Year         0
Month        0
tsunami      0
dtype: int64

In [17]:
df[df.duplicated()]

Empty DataFrame
Columns: [magnitude, cdi, mmi, sig, nst, dmin, gap, depth, latitude, longitude, Year, Month, tsunami]
Index: []

In [18]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
Y_pred = knn.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============KNN===========")
print("accuracy score",accuracy_score(Y_pred,Y_test)*100)
print("precision_score",precision_score(Y_pred,Y_test)*100)
print("recall_score",recall_score(Y_pred,Y_test)*100)
print("f1_score",f1_score(Y_pred,Y_test)*100)

=============KNN===========
accuracy score 84.07643312101911
precision_score 89.39393939393939
recall_score 76.62337662337663
f1_score 82.51748251748252

In [23]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)
Y_predict = nb.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============naive bayes===========")

print("accuracy score",accuracy_score(Y_predict,Y_test)*100)
print("precision_score",precision_score(Y_predict,Y_test)*100)
print("recall_score",recall_score(Y_predict,Y_test)*100)
print("f1_score",f1_score(Y_predict,Y_test)*100)

=============naive bayes===========
accuracy score 82.80254777070064
precision_score 92.42424242424242
recall_score 73.49397590361446
f1_score 81.87919463087249

In [25]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_predict2 = rf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("=============Random Forest===========")

print("accuracy score",accuracy_score(Y_predict2,Y_test)*100)
print("precision_score",precision_score(Y_predict2,Y_test)*100)
print("recall_score",recall_score(Y_predict2,Y_test)*100)
print("f1_score",f1_score(Y_predict2,Y_test)*100)

=============Random Forest===========
accuracy score 91.71974522292994
precision_score 95.45454545454545
recall_score 86.3013698630137
f1_score 90.64748201438849