In [194]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [195]:
df = pd.read_csv(r"C:\Users\edwin\OneDrive\Desktop\development_journey\ML_project\synthetic_fraud_dataset.csv")

In [196]:
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,...,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,...,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,TXN_199,USER_2734,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,...,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,...,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,TXN_39489,USER_2014,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,...,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [197]:
df.drop(columns=["Risk_Score"],inplace=True,axis=0)

In [198]:
df.isnull().sum()

Transaction_ID                  0
User_ID                         0
Transaction_Amount              0
Transaction_Type                0
Timestamp                       0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
IP_Address_Flag                 0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Avg_Transaction_Amount_7d       0
Failed_Transaction_Count_7d     0
Card_Type                       0
Card_Age                        0
Transaction_Distance            0
Authentication_Method           0
Is_Weekend                      0
Fraud_Label                     0
dtype: int64

In [199]:
df.dtypes

Transaction_ID                   object
User_ID                          object
Transaction_Amount              float64
Transaction_Type                 object
Timestamp                        object
Account_Balance                 float64
Device_Type                      object
Location                         object
Merchant_Category                object
IP_Address_Flag                   int64
Previous_Fraudulent_Activity      int64
Daily_Transaction_Count           int64
Avg_Transaction_Amount_7d       float64
Failed_Transaction_Count_7d       int64
Card_Type                        object
Card_Age                          int64
Transaction_Distance            float64
Authentication_Method            object
Is_Weekend                        int64
Fraud_Label                       int64
dtype: object

In [200]:
df[df.duplicated()]

Empty DataFrame
Columns: [Transaction_ID, User_ID, Transaction_Amount, Transaction_Type, Timestamp, Account_Balance, Device_Type, Location, Merchant_Category, IP_Address_Flag, Previous_Fraudulent_Activity, Daily_Transaction_Count, Avg_Transaction_Amount_7d, Failed_Transaction_Count_7d, Card_Type, Card_Age, Transaction_Distance, Authentication_Method, Is_Weekend, Fraud_Label]
Index: []

In [201]:
df.drop(columns=["Transaction_ID","User_ID"],inplace=True,axis=0)

In [202]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [203]:
df['Year'] = df['Timestamp'].dt.year
df['Month'] = df['Timestamp'].dt.month
df['Day'] = df['Timestamp'].dt.day
df['Hour'] = df['Timestamp'].dt.hour
df['Minute'] = df['Timestamp'].dt.minute

In [204]:
df.drop(columns=["Timestamp"],inplace=True,axis=0)

In [205]:
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,...,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label,Year,Month,Day,Hour,Minute
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,...,65,883.17,Biometric,0,0,2023,8,14,19,30
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,0,13,478.76,...,186,2203.36,Password,0,1,2023,6,7,4,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,...,226,1909.29,Biometric,0,1,2023,6,20,15,25
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,0,8,182.48,...,76,1311.86,OTP,0,1,2023,12,7,0,31
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,...,140,966.98,Password,1,1,2023,11,11,23,44

In [206]:
df.columns

Index(['Transaction_Amount', 'Transaction_Type', 'Account_Balance',
       'Device_Type', 'Location', 'Merchant_Category', 'IP_Address_Flag',
       'Previous_Fraudulent_Activity', 'Daily_Transaction_Count',
       'Avg_Transaction_Amount_7d', 'Failed_Transaction_Count_7d', 'Card_Type',
       'Card_Age', 'Transaction_Distance', 'Authentication_Method',
       'Is_Weekend', 'Fraud_Label', 'Year', 'Month', 'Day', 'Hour', 'Minute'],
      dtype='object')

In [207]:
# Automatically selects object columns and prints their value counts
for col in df.select_dtypes(include='object').columns:
    print(f"--- Value Counts for {col} ---")
    print(df[col].value_counts())
    print("\n")

--- Value Counts for Transaction_Type ---
Transaction_Type
POS               12549
Online            12546
ATM Withdrawal    12453
Bank Transfer     12452
Name: count, dtype: int64


--- Value Counts for Device_Type ---
Device_Type
Tablet    16779
Mobile    16640
Laptop    16581
Name: count, dtype: int64


--- Value Counts for Location ---
Location
Tokyo       10208
Mumbai       9994
London       9945
Sydney       9938
New York     9915
Name: count, dtype: int64


--- Value Counts for Merchant_Category ---
Merchant_Category
Clothing       10033
Groceries      10019
Travel         10015
Restaurants     9976
Electronics     9957
Name: count, dtype: int64


--- Value Counts for Card_Type ---
Card_Type
Mastercard    12693
Visa          12560
Amex          12419
Discover      12328
Name: count, dtype: int64


--- Value Counts for Authentication_Method ---
Authentication_Method
Biometric    12591
PIN          12586
Password     12457
OTP          12366
Name: count, dtype: int64

In [208]:
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,...,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label,Year,Month,Day,Hour,Minute
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,...,65,883.17,Biometric,0,0,2023,8,14,19,30
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,0,13,478.76,...,186,2203.36,Password,0,1,2023,6,7,4,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,...,226,1909.29,Biometric,0,1,2023,6,20,15,25
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,0,8,182.48,...,76,1311.86,OTP,0,1,2023,12,7,0,31
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,...,140,966.98,Password,1,1,2023,11,11,23,44

In [209]:
X = df.drop(columns=['Fraud_Label'])
Y = df['Fraud_Label']

In [210]:
X.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,...,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Year,Month,Day,Hour,Minute
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,...,Amex,65,883.17,Biometric,0,2023,8,14,19,30
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,0,13,478.76,...,Mastercard,186,2203.36,Password,0,2023,6,7,4,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,...,Visa,226,1909.29,Biometric,0,2023,6,20,15,25
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,0,8,182.48,...,Visa,76,1311.86,OTP,0,2023,12,7,0,31
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,...,Mastercard,140,966.98,Password,1,2023,11,11,23,44

In [211]:
Y.head()

0    0
1    1
2    1
3    1
4    1
Name: Fraud_Label, dtype: int64

In [212]:
X.dtypes

Transaction_Amount              float64
Transaction_Type                 object
Account_Balance                 float64
Device_Type                      object
Location                         object
Merchant_Category                object
IP_Address_Flag                   int64
Previous_Fraudulent_Activity      int64
Daily_Transaction_Count           int64
Avg_Transaction_Amount_7d       float64
Failed_Transaction_Count_7d       int64
Card_Type                        object
Card_Age                          int64
Transaction_Distance            float64
Authentication_Method            object
Is_Weekend                        int64
Year                              int32
Month                             int32
Day                               int32
Hour                              int32
Minute                            int32
dtype: object

In [213]:
df["Is_Weekend"].value_counts()

Is_Weekend
0    35018
1    14982
Name: count, dtype: int64

### One Hot Encoding

In [214]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [215]:
categorical_cols = X.select_dtypes(include='object').columns

ct = ColumnTransformer(
    [('encoder', OneHotEncoder(), categorical_cols)],
    remainder='passthrough'
)
X=pd.DataFrame(ct.fit_transform(X))

In [216]:
X.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
32    float64
33    float64
34    float64
35    float64
36    float64
37    float64
38    float64
39    float64
dtype: object

In [217]:
Y.value_counts()

Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

In [218]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [219]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [220]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,Y_train)
Y_predict_knn = knn.predict(X_test)

In [221]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== KNN =====")

print("accuracy score",accuracy_score(Y_predict_knn,Y_test)*100)
print("precision_score",precision_score(Y_predict_knn,Y_test)*100)
print("recall_score",recall_score(Y_predict_knn,Y_test)*100)
print("f1_score",f1_score(Y_predict_knn,Y_test)*100)

===== KNN =====
accuracy score 67.03
precision_score 26.955177743431218
recall_score 48.28349944629014
f1_score 34.59631025590161

In [222]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)
Y_predict_nb = nb.predict(X_test)

In [223]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== naive bayes =====")


print("accuracy score",accuracy_score(Y_predict_nb,Y_test)*100)
print("precision_score",precision_score(Y_predict_nb,Y_test)*100)
print("recall_score",recall_score(Y_predict_nb,Y_test)*100)
print("f1_score",f1_score(Y_predict_nb,Y_test)*100)

===== naive bayes =====
accuracy score 85.13
precision_score 64.14219474497682
recall_score 86.38634471273939
f1_score 73.62072024126309

In [224]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="entropy",max_depth=4)
dt.fit(X_train,Y_train)
Y_predict_dt = dt.predict(X_test)

In [225]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== decision tree =====")

print("accuracy score",accuracy_score(Y_predict_dt,Y_test)*100)
print("precision_score",precision_score(Y_predict_dt,Y_test)*100)
print("recall_score",recall_score(Y_predict_dt,Y_test)*100)
print("f1_score",f1_score(Y_predict_dt,Y_test)*100)

===== decision tree =====
accuracy score 87.72999999999999
precision_score 62.0710973724884
recall_score 100.0
f1_score 76.59736791913026

In [226]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_predict_rf = rf.predict(X_test)

In [227]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== Random Forest =====")

print("accuracy score",accuracy_score(Y_predict_rf,Y_test)*100)
print("precision_score",precision_score(Y_predict_rf,Y_test)*100)
print("recall_score",recall_score(Y_predict_rf,Y_test)*100)
print("f1_score",f1_score(Y_predict_rf,Y_test)*100)

===== Random Forest =====
accuracy score 87.72999999999999
precision_score 62.0710973724884
recall_score 100.0
f1_score 76.59736791913026

In [228]:
from sklearn.ensemble import AdaBoostClassifier
ab = AdaBoostClassifier()
ab.fit(X_train,Y_train)
Y_predict_ada = ab.predict(X_test)

In [229]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== ADA BOOST =====")

print("accuracy score",accuracy_score(Y_predict_ada,Y_test)*100)
print("precision_score",precision_score(Y_predict_ada,Y_test)*100)
print("recall_score",recall_score(Y_predict_ada,Y_test)*100)
print("f1_score",f1_score(Y_predict_ada,Y_test)*100)

===== ADA BOOST =====
accuracy score 87.72999999999999
precision_score 62.0710973724884
recall_score 100.0
f1_score 76.59736791913026

In [230]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()
gb.fit(X_train,Y_train)
Y_predict_gb = gb.predict(X_test)

In [231]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== GRADIENT BOOST =====")

print("accuracy score",accuracy_score(Y_predict_gb,Y_test)*100)
print("precision_score",precision_score(Y_predict_gb,Y_test)*100)
print("recall_score",recall_score(Y_predict_gb,Y_test)*100)
print("f1_score",f1_score(Y_predict_gb,Y_test)*100)

===== GRADIENT BOOST =====
accuracy score 87.68
precision_score 62.0710973724884
recall_score 99.75161450571287
f1_score 76.52439024390245

In [232]:
from xgboost import XGBClassifier
xg = XGBClassifier()
xg.fit(X_train,Y_train)
Y_predict_xg = xg.predict(X_test)

In [233]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

print("===== XG BOOST =====")

print("accuracy score",accuracy_score(Y_predict_xg,Y_test)*100)
print("precision_score",precision_score(Y_predict_xg,Y_test)*100)
print("recall_score",recall_score(Y_predict_xg,Y_test)*100)
print("f1_score",f1_score(Y_predict_xg,Y_test)*100)

===== XG BOOST =====
accuracy score 87.42999999999999
precision_score 62.132921174652246
recall_score 98.43290891283057
f1_score 76.17964752700398