In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("spotify_preprocessing_dataset.csv")
df

,Track,Artist,Genre,DurationSec,Popularity,Danceability,Energy,Tempo,Loudness,Acousticness,StreamsMillions
0,Blinding Lights,The Weeknd,Pop,303,73,0.46,0.56,108,-10.7,0.10,2283
1,Levitating,Dua Lipa,Pop,162,88,0.66,0.42,107,-9.9,0.52,2348
2,Shape of You,Ed Sheeran,Pop,190,92,0.77,0.72,108,-8.0,0.24,76
3,Stay,The Kid LAROI,Hip-Hop,180,92,0.66,0.56,107,-3.4,0.29,429
4,Peaches,Justin Bieber,R&B,237,73,0.63,0.60,113,-4.7,0.62,2246
5,Bad Guy,Billie Eilish,Alternative,171,99,0.64,0.72,160,-6.4,0.73,2414
6,Sunflower,Post Malone,Hip-Hop,189,92,0.48,0.78,178,-9.4,0.08,1003
7,Closer,The Chainsmokers,EDM,165,82,0.59,0.77,126,-10.5,0.31,1143
8,Watermelon Sugar,Harry Styles,Pop,319,99,0.79,0.44,161,-10.5,0.62,719
9,As It Was,Harry Styles,Pop,258,82,0.58,0.94,168,-7.0,0.59,279
10,Senorita,Shawn Mendes,Latin Pop,198,96,0.47,0.58,114,-11.4,0.78,2373
11,Believer,Imagine Dragons,Rock,220,76,0.78,0.63,162,-7.9,0.23,1060
12,Industry Baby,Lil Nas X,Rap,283,87,0.58,0.74,154,-8.4,0.19,616
13,Happier Than Ever,Billie Eilish,Alternative,270,85,0.50,0.43,94,-10.6,0.14,1779
14,Dance Monkey,Tones and I,Indie Pop,292,72,0.64,0.75,139,-7.2,0.83,97
15,Perfect,Ed Sheeran,Pop,314,93,0.51,0.91,176,-9.6,0.55,506

In [4]:
df.shape

(16, 11)

In [5]:
df.columns

Index(['Track', 'Artist', 'Genre', 'DurationSec', 'Popularity', 'Danceability',
       'Energy', 'Tempo', 'Loudness', 'Acousticness', 'StreamsMillions'],
      dtype='object')

In [7]:
df.head()

,Track,Artist,Genre,DurationSec,Popularity,Danceability,Energy,Tempo,Loudness,Acousticness,StreamsMillions
0,Blinding Lights,The Weeknd,Pop,303,73,0.46,0.56,108,-10.7,0.10,2283
1,Levitating,Dua Lipa,Pop,162,88,0.66,0.42,107,-9.9,0.52,2348
2,Shape of You,Ed Sheeran,Pop,190,92,0.77,0.72,108,-8.0,0.24,76
3,Stay,The Kid LAROI,Hip-Hop,180,92,0.66,0.56,107,-3.4,0.29,429
4,Peaches,Justin Bieber,R&B,237,73,0.63,0.60,113,-4.7,0.62,2246

In [8]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [9]:
X

,Track,Artist,Genre,DurationSec,Popularity,Danceability,Energy,Tempo,Loudness,Acousticness
0,Blinding Lights,The Weeknd,Pop,303,73,0.46,0.56,108,-10.7,0.10
1,Levitating,Dua Lipa,Pop,162,88,0.66,0.42,107,-9.9,0.52
2,Shape of You,Ed Sheeran,Pop,190,92,0.77,0.72,108,-8.0,0.24
3,Stay,The Kid LAROI,Hip-Hop,180,92,0.66,0.56,107,-3.4,0.29
4,Peaches,Justin Bieber,R&B,237,73,0.63,0.60,113,-4.7,0.62
5,Bad Guy,Billie Eilish,Alternative,171,99,0.64,0.72,160,-6.4,0.73
6,Sunflower,Post Malone,Hip-Hop,189,92,0.48,0.78,178,-9.4,0.08
7,Closer,The Chainsmokers,EDM,165,82,0.59,0.77,126,-10.5,0.31
8,Watermelon Sugar,Harry Styles,Pop,319,99,0.79,0.44,161,-10.5,0.62
9,As It Was,Harry Styles,Pop,258,82,0.58,0.94,168,-7.0,0.59
10,Senorita,Shawn Mendes,Latin Pop,198,96,0.47,0.58,114,-11.4,0.78
11,Believer,Imagine Dragons,Rock,220,76,0.78,0.63,162,-7.9,0.23
12,Industry Baby,Lil Nas X,Rap,283,87,0.58,0.74,154,-8.4,0.19
13,Happier Than Ever,Billie Eilish,Alternative,270,85,0.50,0.43,94,-10.6,0.14
14,Dance Monkey,Tones and I,Indie Pop,292,72,0.64,0.75,139,-7.2,0.83
15,Perfect,Ed Sheeran,Pop,314,93,0.51,0.91,176,-9.6,0.55